spring:
    application:
        name: facial-id
    http:
        multipart:
            max-file-size:
                10240KB
            max-request-size:
                10240KB                    
endpoints:
    enabled: true
    health:
        enabled: true
    loggers:
        sensitive: false
        enabled: true
management:
    security:
        enabled: false
server:
    hostname: localhost
    port: 8080
    servlet-path: /
    tomcat:
        remote_ip_header: x-forwarded-for
        protocol_header: x-forwarded-proto
        internal-proxies: 192\.168\.\d{1,3}\.\d{1,3}
    use-forward-headers: true
    error:
        whitelabel:
            enabled: false
            
    
face:
    api:
        key: Xx4_MwZ8lFGUcZO-NiS-eqVFwCflyjM2
        secret: CREATE_CONFIG_FOLDER_ON_ROOT_AND_OVERWRITE_THIS_PROPERTY
        base:   CREATE_CONFIG_FOLDER_ON_ROOT_AND_OVERWRITE_THIS_PROPERTY
    faceset:
        outerId:
            test